### ISSUE TITLE
functions not loading into namespace

### ISSUE THREAD

**Issue by middleprofessor** [JLSteenwyk/ggpubfigs#1]
This package looks great and thanks for the work. I downloaded and installed.

1) with package loaded, this `scale_fill_manual(values = friendly_pal("contrast_three")) ` returns this error

Error in friendly_pal("contrast_three") : 
  could not find function "friendly_pal"

2) this `scale_fill_manual(values = ggpubfigs::friendly_pal("contrast_three")) ` returns this error
Error: 'friendly_pal' is not an exported object from 'namespace:ggpubfigs'

I hope this isn't specific to my setup.

**Comment by middleprofessor** [comment]
Fixed! Thanks!

**Comment by JLSteenwyk** [comment]
Thanks Jeff. I had forgotten to run `devtools::document()` prior to announcing the package...my mistake. Thank you for helping me resolve this issue!

**Comment by Maooz-a** [comment]
hey so im basically new to R and when i run the install package code `devtools::install_github("JLSteenwyk/ggpubfigs")` it gives error as 
`Error in loadNamespace(x) : there is no package called ‘devtools’`

What could be the issue? I dont know much :)

**Comment by JLSteenwyk** [comment]
Hi @Maooz-a,

The package `devtools` needs to be installed first. 

You can install `devtools` using this command: `install.packages("devtools", dep=T)`.

Thanks for using ggpubfigs! 

Cheers,

Jacob
